spring:
  application:
    name: sb06-deokhugam-team01
  cloud:
    aws:
      credentials:
        access-key: ${AWS_S3_ACCESS_KEY:aaa}
        secret-key: ${AWS_S3_SECRET_KEY:aaa}
      region:
        static: ${ap-northeast-2:ap-northeast-2}
      s3:
        bucket: ${AWS_S3_BUCKET:aaa}
        presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:PT10H}
  config:
    import: optional:file:${user.dir}/.env[.properties]
  datasource:
    url: jdbc:h2:mem:deokhugam;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    username: ${SPRING_DATASOURCE_USERNAME:deokhugam}
    password: ${SPRING_DATASOURCE_PASSWORD:deokhugam}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
naver:
  api:
    endpoint: https://openapi.naver.com/v1/search/book_adv.json
    client-id: ${NAVER_API_CLIENT_ID:aaa}
    client-secret: ${NAVER_API_CLIENT_SECRET:aaa}
ocr:
  space:
    api:
      endpoint: https://api.ocr.space/parse/image
      key: ${OCR_SPACE_API_KEY:aaa}
