spring:
  application:
    name: sb06-deokhugam-team01
  cloud:
    aws:
      credentials:
        access-key: ${AWS_S3_ACCESS_KEY}
        secret-key: ${AWS_S3_SECRET_KEY}
      region:
        static: ${ap-northeast-2:ap-northeast-2}
      s3:
        bucket: ${AWS_S3_BUCKET}
        presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:PT10H}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/deokhugam}
    username: ${SPRING_DATASOURCE_USERNAME:deokhugam}
    password: ${SPRING_DATASOURCE_PASSWORD:deokhugam}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
naver:
  api:
    endpoint: https://openapi.naver.com/v1/search/book_adv.json
    client-id: ${NAVER_API_CLIENT_ID}
    client-secret: ${NAVER_API_CLIENT_SECRET}
ocr:
  space:
    api:
      endpoint: https://api.ocr.space/parse/image
      key: ${OCR_SPACE_API_KEY}