name: CI

on:
  push:
    branches: [ "test" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: check pwd
        run: pwd

      - name: make env files
        run: |
          echo "NAVER_API_CLIENT_ID = ${{secrets.NAVER_API_CLIENT_ID}}" >> .env
          echo "NAVER_API_CLIENT_SECRET = ${{secrets.NAVER_API_CLIENT_SECRET}}" >> .env
          echo "OCR_SPACE_API_KEY = ${{secrets.OCR_SPACE_API_KEY}}" >> .env

      - name: check env files
        run: cat ./.env

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build and test
        run: ./gradlew clean build

      - name: Test with Gradle
        run: ./gradlew test jacocoTestReport

      - name: Generate JacCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv

      - name: Commit and push badge
        if: success()
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          messasge: 'commit badge'
          add: '*.svg'